/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e0e3e5",
        surface: "#f7f9fb",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#004d6a",
        "on-tertiary-container": "#7073ff",
        "tertiary-container": "#07006c",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "on-error": "#ffffff",
        "on-primary-fixed": "#1b1c1c",
        "on-secondary-fixed": "#001e2c",
        "secondary-fixed-dim": "#7bd0ff",
        "on-surface": "#191c1e",
        "surface-container-highest": "#e0e3e5",
        "on-primary-container": "#848483",
        "inverse-primary": "#c8c6c6",
        "inverse-on-surface": "#eff1f3",
        "on-primary-fixed-variant": "#474747",
        "primary-fixed-dim": "#c8c6c6",
        secondary: "#00668a",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-dim": "#d8dadc",
        "on-secondary-fixed-variant": "#004c69",
        "surface-tint": "#5e5e5e",
        "primary-fixed": "#e4e2e2",
        "tertiary-fixed-dim": "#c0c1ff",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#1b1c1c",
        "secondary-container": "#40c2fd",
        primary: "#000000",
        "error-container": "#ffdad6",
        "on-surface-variant": "#45464d",
        "surface-container-high": "#e6e8ea",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        error: "#ba1a1a",
        "secondary-fixed": "#c4e7ff",
        outline: "#76777d",
        tertiary: "#000000",
        "surface-bright": "#f7f9fb",
        "on-tertiary-fixed": "#07006c",
        "on-background": "#191c1e",
        "on-error-container": "#93000a",
        background: "#f7f9fb",
        "outline-variant": "#c6c6cd",
        "inverse-surface": "#2d3133",
        "tertiary-fixed": "#e1e0ff",
        navy: "#0f172a",
      },
      borderRadius: {
        DEFAULT: "8px",
        lg: "8px",
        xl: "12px",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        "section-gap": "160px",
        "margin-mobile": "20px",
        gutter: "24px",
        "container-max": "1200px",
      },
      fontFamily: {
        display: ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter"],
        "label-sm": ["Geist"],
        "headline-lg": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        display: [
          "72px",
          { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" },
        ],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-sm": [
          "13px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "headline-lg": [
          "48px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-md": [
          "30px",
          { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      boxShadow: {
        ambient:
          "0 4px 6px -1px rgba(15, 23, 42, 0.05), 0 24px 38px -10px rgba(15, 23, 42, 0.05)",
      },
      backgroundImage: {
        "gradient-primary": "linear-gradient(180deg, #38BDF8 0%, #0EA5E9 100%)",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
